services:
  py-load:
    build:
      context: .
      dockerfile: Dockerfile
    image: py-nbaload
    container_name: pynba
    networks:
      dbnet:
        ipv4_address: 10.0.13.211
    command: ["python3", "src/main.py"]

networks:
  dbnet:
    external: true
